import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const lato = Lato({ weight: ["100", "300", "400", "700", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <main className="h-screen bg-gradient-to-b from-[#141e30] via-[#243b55] to-[#243b55]">
          {children}
        </main>
      </body>
    </html>
  );
}
